### ISSUE TITLE
0.4.2 release checklist

### ISSUE THREAD

**Issue by felixboehm** [owncloud/guests#128]
Small Release contains only  
- PR fixing the settings.
- improving texts
- [New registration](https://github.com/owncloud/guests/pull/109)

QA 
- [x] create release branch: https://github.com/owncloud/guests/pull/146
- [x] bump version to 0.4.2
- [x] create testplan and test cases Link: https://github.com/owncloud/guests/issues/132
- [x] test and document in testplan. Final release "Go"

Marketing
- [x] Write texts, adapt info.xml https://github.com/owncloud/guests/pull/131
- [x] Short blog post on owncloud.org about the changes/roundoffs and giving some hint on future plans regarding guests app @pmaier

Build
- [x] makefile for the app https://github.com/owncloud/guests/issues/24
- [x] Adapt changelog to keepachangelog structure, e.g. https://github.com/owncloud/customgroups/blob/master/CHANGELOG.md
- [x] Update Changelog https://github.com/owncloud/guests/pull/135/files
- [x] Change license to GPLv2 @hodyroff https://github.com/owncloud/guests/issues/143
- [x] Change CHANGELOG.md 'Unreleased' to '0.4.2' and add a new 'Unreleased' section
- [x] sign and build tarball
- [x] upload to marketplace
- [x] rename QA milestone to version number

**Comment by pmaier1** [comment]
Once https://github.com/owncloud/guests/pull/131 is merged we are ready set here. Go for teh release!

**Comment by davitol** [comment]
I guess guest app is ready for signing  and building the tarball

**Comment by cortho** [comment]
Note: for the release, in CHANGELOG.md, Unreleased should be changed for the actual version and the compare link should be added.
