### ISSUE TITLE
Testplan

### ISSUE THREAD

**Issue by felixboehm** [owncloud/guests#132]
Please add test cases for / test with fokus on 
- [New registration](https://github.com/owncloud/guests/pull/109)

## 'Guest App' Test Plan

- Run Testplan with encryption enabled

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Guest app via CLI using ```occ app:enable guests``` | The apps is enabled | ✅  |
Disable Guest app via CLI using ```occ app:disable guests``` | The apps is disabled | ✅|
**Add Guest User in sharetabview** |  |   |
|  |   |
Create a guest user via email |  | ✅ |
Create a guest user via email sharing from another guest user |  | ✅   |
Create a guest user via email sharing from an LDAP user |  | ✅ |
Create a guest user via email sharing from an Shibboleth user | | ❓   | https://github.com/owncloud/user_shibboleth/issues/191
Try to create a guest user via email when a server email is not set or it is invalid|  An error message should be shown | ❌   |
Try to create a guest user via email with an invalid email format | An error message should be shown | ❌   |
Try to create a guest user via email with an already used email | An warning about a username with that email already exists should be shown | ✅  |
Try to create a guest user via email already registered by email | A warning about the token is invalid should be shown | ✅ |
Create a guest user via email using a password that fits password policy | Check that the user receives the email and can register into oC | ✅  | 
Create a guest user via email using a password that doesn't fit password policy | Check that the user receives the email and cannot register into oC. A warning related to password policy should be shown | ✅  |
**Users Menu** |  |   |
|  |   |
Delete a guest user in user's menu | The user is deleted and no longer available in oC. Check that user disappears from sharetabviews | ✅ |
Try to create a guest user in users menu adding it to the guest_group| The user should not be created. A warning should be shown | ✅  |
Change the guest user's password in users menu | The new password is set for the guest user | ✅ |
**Guest User account**|  |   |
|  |   |
Log in the guest user account  | Check that the shared file/folder appears with the right permissions | ✅  |
Reshare a folder with folder permissions to another guest user | Check that the shared folder works fine | :✅ |
In personal page, change users email. Then as admin try to create a new guest user with the old mail  | Check that the mail which was used for the register is kept | ✅  |
**Settings page**|  |   |
|  |   |
Change Guest Group name  | The group name for guest is changed. Check this change in Users Page and the shares are kept | ✅ |
Set Guest Group name as empty  | A warning error should be shown and the previous name should be kept | ✅  |
Limit guest access to an app whitelist checked, modify the list and save  | Check that only apps listed are available for guests users | ✅  |
**WebUI and browsers**|  |   |
|  |   |
Check that guests menu in sharing section works fine using FireFox as browser |  | ✅:  |
Check that guests menu in sharing section works fine using Chrome as browser |  | ✅  |
Check that guests menu in sharing section works fine using IE11 as browser |  | ✅ |
Check that guests menu in sharing section works fine using Edge as browser |  | ✅  |
Check that guests menu in sharing section works fine using Safari as browser |  | ✅  |

**Comment by davitol** [comment]
Related Issues:

- [ ] Create guest by typing email address directly https://github.com/owncloud/guests/issues/58
- [ ] Improve naming of guest accounts https://github.com/owncloud/guests/issues/69
- [ ] admin cannot see, when a guest user's password token is expired https://github.com/owncloud/guests/issues/88
- [ ] Move username generation to backend https://github.com/owncloud/guests/issues/89
- [ ] lostpassword expires too early https://github.com/owncloud/guests/issues/93
