### ISSUE TITLE
0.5 Release Plan 

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#176]
## Reasons:
- Major usability change: Remove modal and allow guest creation only via entering mail https://github.com/owncloud/guests/pull/149
- Compatibility with password_policy https://github.com/owncloud/guests/pull/160
- E-Mail address validation https://github.com/owncloud/guests/pull/170
- Never offer guest user creation when mail address is associated with an existing user from any user backend https://github.com/owncloud/guests/pull/168
- Whitelisting/restriction of apps/features partly fixed https://github.com/owncloud/guests/pull/165
- More fixes

## QA
- [x] create release branch
- [x] bump version to 0.5 https://github.com/owncloud/guests/pull/182
- [x] create testplan and test cases https://github.com/owncloud/guests/issues/177
- [x] test and document in testplan. Final release "Go"

#### Pending to be merged before QA can start:

- [x] https://github.com/owncloud/guests/pull/168
- [x] https://github.com/owncloud/guests/pull/170
- [x] https://github.com/owncloud/guests/pull/158
- [x] https://github.com/owncloud/guests/pull/160
- [x] https://github.com/owncloud/guests/pull/165
- [x] https://github.com/owncloud/guests/pull/161
- [x] https://github.com/owncloud/guests/pull/151

## Marketing 
- [x] Check/adapt info.xml stuff https://github.com/owncloud/guests/issues/164
- [x] Blog post to communicate changes @pmaier

## Build
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] Create tag for '$version' (by @patrickjahns)
- [x] Sign and build tarball (by @patrickjahns)
- [x] Upload to marketplace (by @patrickjahns)
- [x] Rename QA milestone to '$version'  (by @patrickjahns)

## Specifics
- Release needs to be aligned with https://github.com/owncloud/password_policy/issues/110
- [x] waiting for domain blacklist for guest user creation https://github.com/owncloud/guests/issues/173

**Comment by davitol** [comment]
@pmaier1 @cortho @PVince81

**Comment by pmaier1** [comment]
Milestone sorted out now. I want to have this release as 0.5 as there are major changes. 
According to @PVince81 we should wait for the domain blacklist for guest user creation which should be finished soon.
@cortho for changelog?

**Comment by PVince81** [comment]
changelog PR here https://github.com/owncloud/guests/pull/178

**Comment by patrickjahns** [comment]
@pmaier1 
released to marketplace - feel free to close when you see fit

**Comment by pmaier1** [comment]
Good job, guys! Blog post will come tomorrow at lunch time.
