### ISSUE TITLE
Guests 0.6.2 release checklist

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#223]
### Reason
- [x] fix for events not being triggered properly: https://github.com/owncloud/guests/pull/243
- [x] other minor fixes
- [x] fix acceptance tests https://github.com/owncloud/guests/issues/247
- ~~tech debt ? https://github.com/owncloud/guests/issues/235~~

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch release-0.6.0
- [x] Create "0.6.0 Testplan" @davitol  https://github.com/owncloud/guests/issues/248
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/guests/pull/244
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/guests/pull/244
- [x] Create github tag for 'v$version'
- [x] Build and sign tarball from github tag 'v$version'
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/guests/pull/260 https://github.com/owncloud/guests/pull/261

**Comment by PVince81** [comment]
need to sort out test failure: https://github.com/owncloud/guests/issues/247

**Comment by PVince81** [comment]
got trouble uploading to marketplace because max-version 11.0.0.0 not supported by marketplace.

I created another branch release-0.6.1 with adjusted version. We'll release that instead.
@davitol please test

**Comment by PVince81** [comment]
then got trouble uploading with max-version=10. 

so we settle on max-version=10.1 and released as guests-0.6.2
