### ISSUE TITLE
Tracking testing results for Guests 0.7.0

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#276]
Tested in ownCloud 10.0.10 and using the tarball provided here: https://cloud.owncloud.com/index.php/s/hOji9zbJYHyltRE

## Changelog
 - [x] Small bugfix #264 **Test stesps: User opens password page for guests app and  user_autofocus log does not longer appears in owncloud.log**
 - [x] Tech debt in preparation for API removal: #245 **Untested, due to it doesn't change behavior, just implementation. App still works as expected so everything is ok**
 - [x] Guests now cannot create other guests: #224 **Tested trying to create a new guest users when i am logged aas a guest**
 - [x] Set max version to 10 for Semver
