### ISSUE TITLE
Guests 0.8.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#289]
### Reason
- [x] Email validation: https://github.com/owncloud/guests/pull/274
- [x] GroupBackend fix for activity loop: https://github.com/owncloud/guests/pull/290
- Note: this release will have min-version=10.1 !
- ~~share_folder issue: https://github.com/owncloud/guests/pull/305~~ core issue
- [x] ~~guest share to other guests should be forbidden in "shared with you" view: https://github.com/owncloud/guests/issues/308~~ => core issue

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "Guests 0.8.0 Testplan" @davitol https://github.com/owncloud/guests/issues/312

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://github.com/owncloud/guests/releases/tag/v0.8.0RC1
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch => https://github.com/owncloud/guests/pull/314

**Comment by PVince81** [comment]
since #274 brings a dependency on core for a minor fix but https://github.com/owncloud/guests/pull/290 is a rather important fix, maybe we should release the latter as 0.7.1

**Comment by PVince81** [comment]
- [ ] consider release of the non-email-validation fixes as Guests 0.7.1

**Comment by PVince81** [comment]
would be good to have https://github.com/owncloud/guests/issues/308 fixed as well

**Comment by PVince81** [comment]
it's a core issue.

ok, so we can move forward with the release

**Comment by PVince81** [comment]
- [ ] Makefile broken, can't run `make dist`: https://github.com/owncloud/guests/issues/309

**Comment by PVince81** [comment]
0.8.0RC1 ready for testing: https://github.com/owncloud/guests/releases/tag/v0.8.0RC1

@davitol

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready

**Comment by PVince81** [comment]
final tarball: https://github.com/owncloud/guests/releases/download/v0.8.0/guests-0.8.0.tar.gz
