### ISSUE TITLE
Tracking Testing results for Guests 0.8.0

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#312]
Tested in ownCloud 10.1 and using the tarball provided here: https://github.com/owncloud/guests/releases/download/v0.8.0RC1/guests-0.8.0RC1.tar.gz

## Changelog
 - [x] Changes core min-version requirement to 10.1.0 - [#274](https://github.com/owncloud/guests/issues/274) @davitol **Test step: Checked the version  in info.xml file**
 - [x] Use email validation functions from core, requires core >= 10.1.0 - [#274](https://github.com/owncloud/guests/issues/274)  @davitol **Tests steps: https://github.com/owncloud/guests/pull/274#issue-233893565**
 - [x] Code style cleanup, now PSR-4 - [#305](https://github.com/owncloud/guests/issues/305) @davitol  **Test steps: Unit tests and https://github.com/owncloud/core/pull/34388#issue-250333356** **Note:** Tested with this PR https://github.com/owncloud/core/pull/34395 unreleased yet. It will come in oC 10.2
