### ISSUE TITLE
Tracking Testing results for Guests 0.8.2

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#349]
Tested in ownCloud 10.3 and using the tarball provided here: https://github.com/owncloud/guests/releases/download/v0.8.2RC1/guests-0.8.2RC1.tar.gz

## 'Guest App' Test Plan

- Run Testplan with encryption enabled

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Guest app via CLI using ```occ app:enable guests``` | The apps is enabled | ✅   |
Disable Guest app via CLI using ```occ app:disable guests``` | The apps is disabled | ✅  |
**Add Guest User in sharetabview** |  |   |
|  |   |
Create a guest user via email |  | ✅ |
Try to create a guest user via email sharing from another guest user |  | ✅  | Guest user is not created
Create a guest user via email sharing from an LDAP user |  | ✅ |
Create a guest user via email sharing from an Shibboleth user | | :construction:  |
Try to create a guest user via email when a server email is not set or it is invalid|  Guest user option does not appear | ✅ |
Try to create a guest user via email with an invalid email format | Guest user option does not appear | ✅  |
Try to create a guest user via email with an already used email | Guest user should appear as User. Cannot create another guest user | ✅  |
Try to create a guest user via email already registered by email |  Guest user should appear as User. Cannot create another guest user | ✅  |
Create a guest user via email using a password that fits password policy | Check that the user receives the email and can register into oC | ✅  | 
Create a guest user via email using a password that doesn't fit password policy | Check that the user receives the email and cannot register into oC. A warning related to password policy should be shown | ✅  |
**Users Menu** |  |   |
|  |   |
Delete a guest user in user's menu | The user is deleted and no longer available in oC. Check that user disappears from sharetabviews | ✅  |
Try to create a guest user in users menu adding it to the guest_group| The user should not be created. A warning should be shown | ✅  | No warning shown. Cosmetic bug. User is created and seems to be added to guest group. Refreshing the browser solves the issue
Change the guest user's password in users menu | The new password is set for the guest user | ✅  |
**Guest User account**|  |   |
|  |   |
Log in the guest user account  | Check that the shared file/folder appears with the right permissions | ✅ |
**Settings page**|  |   |
|  |   |
Change Guest Group name  | The group name for guest is changed. Check this change in Users Page and the shares are kept |✅  |
Set Guest Group name as empty  | A warning error should be shown and the previous name should be kept |✅ |
Limit guest access to an app whitelist checked, modify the list and save  | Check that only apps listed are available for guests users | ✅ |
**WebUI and browsers**|  |   |
|  |   |
Check that guests menu in sharing section works fine using FireFox as browser |  | ✅  |
Check that guests menu in sharing section works fine using Chrome as browser |  |✅|
Check that guests menu in sharing section works fine using IE11 as browser |  | ✅ |
Check that guests menu in sharing section works fine using Edge as browser |  | ✅  |
Check that guests menu in sharing section works fine using Safari as browser |  | ✅  |

**Comment by davitol** [comment]
## Changelog

### Fixed

- [ ] Creation of guest shares are now case insensitive for Upper/lowercased emails  - [#326](https://github.com/owncloud/guests/pull/326)

### Changed

- [ ] Removed guest label in drop down to adjust with core display changes - [#337](https://github.com/owncloud/guests/pull/337)

**Comment by davitol** [comment]
### Issues found while QA

- [ ] Modify default apps whitelist for guest users deleting https://github.com/owncloud/guests/issues/350
