### ISSUE TITLE
Guests 0.9.1

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/guests#422]
### Reason

- [ ] Whitelist `files_lifecycle` app https://github.com/owncloud/files_lifecycle/issues/243#issuecomment-675951947
- [ ] Check whether we should also add `windows_network_drive` https://github.com/owncloud/enterprise/issues/4074#issuecomment-686296482
- [ ] Rename "Whitelist" to "Allowlist" in the UI
- ~Whitelist `metrics` app https://github.com/owncloud/metrics/issues/67~ NOT NEEDED

### Product approval

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [ ] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" -> #437

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by micbar** [comment]
@HanaGemela @jnweiger whitelisting metrics is not needed.

**Comment by micbar** [comment]
see #67

**Comment by phil-davis** [comment]
dependabot found #423 "Bump http-proxy from 1.17.0 to 1.18.1". In other repos it said "This update includes a security fix" but not here. It looks like there is not a release branch yet, so this will find its way into the release.

**Comment by jnweiger** [comment]
Release done. Thanks!
