### ISSUE TITLE
Improve UX for guest when opening password link

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#64]
- [ ] have the password link redirect to the actual link after creating the account (might need core work to make it possible)
- [ ] have a custom password page with nice labels from the guests app to set the password, but use the "forgot password" controller from core to set it

@IljaN @pmaier1

**Comment by pmaier1** [comment]
Yes! The button on the password page should at least say 'Set password' instead of 'Reset password'

**Comment by IljaN** [comment]
> have the password link redirect to the actual link after creating the account (might need core work to make it possible)

Do you mean that after setting the password being redirected to the login page, logging in *and then* be redirected to the file in one flow?

**Comment by PVince81** [comment]
That would be even better.

But for now I was mostly thinking of having a "redirect=" param for the password forgotten page. The password forgotten page then redirecty to the private link (formerly known as permalink). Since the user is not logged int, the login page will appears with that URL in the "redirect=" section.

To achieve this, one would need to modify core's password reset form to accept a redirect param.

However, I'd prefer we don't touch core. Better is adding a new page here in the guests app with this logic. If that page is also able to login the user directly then it's also nice, but I'd see this as a second step.

The problem with automatically logging in is that we might bump into issues with login handlers like SSO, etc, so auto-login needs to be thought through.

**Comment by PVince81** [comment]
- [ ] prevent sending of "you password has been reset successfully" post-reset email

**Comment by PVince81** [comment]
Also it seems the fact that we use password reset has side effects like the timeout that is too short: https://github.com/owncloud/guests/issues/93

**Comment by cortho** [comment]
New registration process

after the talks with @pmaier1 and @felixboehm we came to those points which can be quickly implemented:

- [ ] Permit creation of guest users by their email address in the sharetabview. (covers #58 #69)
- [ ] In the modal window "Share with guest 'guestuser'" name and email are prefilled with the email address (so the display name can be changed, if desired)
- [ ] actual username creation is performed in the backend (is the lowercase email address) (covers #89)
- [ ] while creating a new guest user, a registerToken instead of lostpassword token is created (thus delivers us from the lostpassword issues) (covers #88 #93)
- [ ] The invitation email template will provide the link to a new route guests.register.*
- [ ] After a guest user submits the password it will be set via UserManager, the registerToken is deleted.

**Comment by cortho** [comment]
@PVince81 I guess we can close this too. Is there anything left, what we want to transfer to a new issue?

**Comment by PVince81** [comment]
@cortho can you tick your checkboxes ? If all is done then this can be closed.

**Comment by cortho** [comment]
sure. done -> closing
